add updating pip's packages

diff --git a/scripts/executable_upd b/scripts/executable_upd
--- a/scripts/executable_upd
+++ b/scripts/executable_upd
@@ -27,7 +27,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='srfnbavh'
+	local first_option all_short_options='srfnbjavh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -38,6 +38,7 @@ _arg_autoremove="off"
 _arg_flatpak="off"
 _arg_neovim="off"
 _arg_bin="off"
+_arg_npm="off"
 _arg_all="off"
 _arg_verbose="on"
 
@@ -45,12 +46,13 @@ _arg_verbose="on"
 print_help()
 {
 	printf '%s\n' "Upd - little wrapper to update system"
-	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-b|--(no-)bin] [-a|--(no-)all] [-v|--(no-)verbose] [-h|--help]\n' "$0"
+	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-b|--(no-)bin] [-j|--(no-)npm] [-a|--(no-)all] [-v|--(no-)verbose] [-h|--help]\n' "$0"
 	printf '\t%s\n' "-s, --system, --no-system: Update system packages (off by default)"
 	printf '\t%s\n' "-r, --autoremove, --no-autoremove: Remove orphans automatically (off by default)"
 	printf '\t%s\n' "-f, --flatpak, --no-flatpak: Update flatpak applications (off by default)"
 	printf '\t%s\n' "-n, --neovim, --no-neovim: Update neovim packages (off by default)"
 	printf '\t%s\n' "-b, --bin, --no-bin: Update cli apps in ~/bin (off by default)"
+	printf '\t%s\n' "-j, --npm, --no-npm: Update globally installed node.js packages (off by default)"
 	printf '\t%s\n' "-a, --all, --no-all: Enables all flags (same as -srfnb) (off by default)"
 	printf '\t%s\n' "-v, --verbose, --no-verbose: Enable verbose output (on by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
@@ -121,6 +123,18 @@ parse_commandline()
 				if test -n "$_next" -a "$_next" != "$_key"
 				then
 					{ begins_with_short_option "$_next" && shift && set -- "-b" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-j|--no-npm|--npm)
+				_arg_npm="on"
+				test "${1:0:5}" = "--no-" && _arg_npm="off"
+				;;
+			-j*)
+				_arg_npm="on"
+				_next="${_key##-j}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-j" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
 			-a|--no-all|--all)
@@ -405,6 +419,11 @@ if [[ $_arg_bin == 'on' ]]; then
     printf "  "
     ansi --red "Error occured."
   fi
+
+
+  for i in $(pip list --outdated | sed '1d;2d' | awk '{print $1}'); do
+    pip install -U "$i"
+  done
 fi
 
 if [[ $_arg_npm == "on" ]]; then
