add updating binaries in ~/bin to `upd` script

diff --git a/scripts/executable_upd b/scripts/executable_upd
--- a/scripts/executable_upd
+++ b/scripts/executable_upd
@@ -4,6 +4,7 @@
 # ARG_OPTIONAL_BOOLEAN([autoremove],[r],[Remove orphans automatically])
 # ARG_OPTIONAL_BOOLEAN([flatpak],[f],[Update flatpak applications])
 # ARG_OPTIONAL_BOOLEAN([neovim],[n],[Update neovim packages])
+# ARG_OPTIONAL_BOOLEAN([bin],[b],[Update cli apps in ~/bin])
 # ARG_OPTIONAL_BOOLEAN([verbose],[v],[Enable verbose output])
 # ARG_HELP([Upd - little wrapper to update system])
 # ARGBASH_GO()
@@ -24,7 +25,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='srfnvh'
+	local first_option all_short_options='srfnbvh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -34,17 +35,19 @@ _arg_system="off"
 _arg_autoremove="off"
 _arg_flatpak="off"
 _arg_neovim="off"
+_arg_bin="off"
 _arg_verbose="off"
 
 
 print_help()
 {
 	printf '%s\n' "Upd - little wrapper to update system"
-	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-v|--(no-)verbose] [-h|--help]\n' "$0"
+	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-b|--(no-)bin] [-v|--(no-)verbose] [-h|--help]\n' "$0"
 	printf '\t%s\n' "-s, --system, --no-system: Update system packages (off by default)"
 	printf '\t%s\n' "-r, --autoremove, --no-autoremove: Remove orphans automatically (off by default)"
 	printf '\t%s\n' "-f, --flatpak, --no-flatpak: Update flatpak applications (off by default)"
 	printf '\t%s\n' "-n, --neovim, --no-neovim: Update neovim packages (off by default)"
+	printf '\t%s\n' "-b, --bin, --no-bin: Update cli apps in ~/bin (off by default)"
 	printf '\t%s\n' "-v, --verbose, --no-verbose: Enable verbose output (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
@@ -104,6 +107,18 @@ parse_commandline()
 					{ begins_with_short_option "$_next" && shift && set -- "-n" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
+			-b|--no-bin|--bin)
+				_arg_bin="on"
+				test "${1:0:5}" = "--no-" && _arg_bin="off"
+				;;
+			-b*)
+				_arg_bin="on"
+				_next="${_key##-b}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-b" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
 			-v|--no-verbose|--verbose)
 				_arg_verbose="on"
 				test "${1:0:5}" = "--no-" && _arg_verbose="off"
@@ -147,6 +162,7 @@ if [[ $_arg_verbose == 'on' ]]; then
   printf "'%s' is %s\\n" 'autoremove' "$_arg_autoremove"
   printf "'%s' is %s\\n" 'flatpak' "$_arg_flatpak"
   printf "'%s' is %s\\n" 'neovim' "$_arg_neovim"
+  printf "'%s' is %s\\n" 'bin' "$_arg_bin"
 fi
 
 # ------------------
@@ -206,6 +222,57 @@ if [[ $_arg_neovim == 'on' ]]; then
   echo
 fi
 
+if [[ $_arg_bin == 'on' ]]; then
+  ansi --blue "Updating binaries in ~/bin..."
+
+  printf "\t"
+  ansi --blue "Updating chezmoi..."
+
+  if chezmoi upgrade; then
+    printf "\t"
+    ansi --green "Chezmoi updated."
+  else
+    printf "\t"
+    ansi --red "Error occured."
+  fi
+
+  echo
+  printf "\t"
+  ansi --blue "Updating addpath..."
+
+  if nim -d:release c ~/scripts/addpath.nim && mv ~/scripts/addpath ~/bin; then
+    printf "\t"
+    ansi --green "Addpath updated."
+  else
+    printf "\t"
+    ansi --red "Error occured."
+  fi
+
+  echo
+  printf "\t"
+  ansi --blue "Updating getpath..."
+
+  if nim -d:release c ~/scripts/getpath.nim && mv ~/scripts/getpath ~/bin; then
+    printf "\t"
+    ansi --green "Getpath updated."
+  else
+    printf "\t"
+    ansi --red "Error occured."
+  fi
+
+  echo
+  printf "\t"
+  ansi --blue "Updating xplr..."
+
+  if kernel_name=$(uname -s) && curl -LO "https://github.com/sayanarijit/xplr/releases/latest/download/xplr-${kernel_name,,}.tar.gz" && tar xzf "xplr-${kernel_name,,}.tar.gz" -C ~/bin && rm -rf "xplr-${kernel_name,,}.tar.gz"; then
+    printf "\t"
+    ansi --green "Xplr updated."
+  else
+    printf "\t"
+    ansi --red "Error occured."
+  fi
+
+fi
 ansi --green "System updated."
 
 
