make `upd` do not print any output from running applications when ran in non-verbose mode

diff --git a/scripts/executable_upd b/scripts/executable_upd
--- a/scripts/executable_upd
+++ b/scripts/executable_upd
@@ -5,6 +5,7 @@
 # ARG_OPTIONAL_BOOLEAN([flatpak],[f],[Update flatpak applications])
 # ARG_OPTIONAL_BOOLEAN([neovim],[n],[Update neovim packages])
 # ARG_OPTIONAL_BOOLEAN([bin],[b],[Update cli apps in ~/bin])
+# ARG_OPTIONAL_BOOLEAN([all],[a],[Enables all flags (same as -srfnb)])
 # ARG_OPTIONAL_BOOLEAN([verbose],[v],[Enable verbose output])
 # ARG_HELP([Upd - little wrapper to update system])
 # ARGBASH_GO()
@@ -25,7 +26,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='srfnbvh'
+	local first_option all_short_options='srfnbavh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -42,12 +43,13 @@ _arg_verbose="off"
 print_help()
 {
 	printf '%s\n' "Upd - little wrapper to update system"
-	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-b|--(no-)bin] [-v|--(no-)verbose] [-h|--help]\n' "$0"
+	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-b|--(no-)bin] [-a|--all] [-v|--(no-)verbose] [-h|--help]\n' "$0"
 	printf '\t%s\n' "-s, --system, --no-system: Update system packages (off by default)"
 	printf '\t%s\n' "-r, --autoremove, --no-autoremove: Remove orphans automatically (off by default)"
 	printf '\t%s\n' "-f, --flatpak, --no-flatpak: Update flatpak applications (off by default)"
 	printf '\t%s\n' "-n, --neovim, --no-neovim: Update neovim packages (off by default)"
 	printf '\t%s\n' "-b, --bin, --no-bin: Update cli apps in ~/bin (off by default)"
+	printf '\t%s\n' "-a, --all: Enables all flags (same as -srfnb) (off by default)"
 	printf '\t%s\n' "-v, --verbose, --no-verbose: Enable verbose output (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
@@ -119,6 +121,25 @@ parse_commandline()
 					{ begins_with_short_option "$_next" && shift && set -- "-b" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
+			-a|--all)
+        _arg_bin="on"
+        _arg_system="on"
+        _arg_neovim="on"
+        _arg_flatpak="on"
+        _arg_autoremove="on"
+				;;
+			-a*)
+        _arg_bin="on"
+        _arg_system="on"
+        _arg_neovim="on"
+        _arg_flatpak="on"
+        _arg_autoremove="on"
+				_next="${_key##-a}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-a" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
 			-v|--no-verbose|--verbose)
 				_arg_verbose="on"
 				test "${1:0:5}" = "--no-" && _arg_verbose="off"
@@ -154,9 +175,6 @@ parse_commandline "$@"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-
-# vvv  PLACE YOUR CODE HERE  vvv
-# shellcheck disable=SC2154
 if [[ $_arg_verbose == 'on' ]]; then
   printf "'%s' is %s\\n" 'system' "$_arg_system"
   printf "'%s' is %s\\n" 'autoremove' "$_arg_autoremove"
@@ -164,8 +182,6 @@ if [[ $_arg_verbose == 'on' ]]; then
   printf "'%s' is %s\\n" 'neovim' "$_arg_neovim"
   printf "'%s' is %s\\n" 'bin' "$_arg_bin"
 fi
-
-# ------------------
 
 ansi --blue "Updating system started..."
 if [[ ($_arg_system == 'on') || ($_arg_autoremove == 'on') ]]; then
@@ -178,7 +194,13 @@ fi
 if [[ $_arg_system == 'on' ]]; then
   ansi --blue "Updating packages..."
 
-  if echo "$password" | sudo -S dnf update -y; then
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="sudo -S dnf update -y"
+  else
+    cmd="sudo -S dnf update -yq"
+  fi
+
+  if echo "$password" | eval "$cmd"; then
     ansi --green "Packages updated."
   else
     ansi --red "Error occured."
@@ -190,7 +212,13 @@ fi
 if [[ $_arg_autoremove == 'on' ]]; then
   ansi --blue "Removing orphans..."
 
-  if echo "$password" | sudo -S dnf autoremove -y; then
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="sudo -S dnf autoremove -y"
+  else
+    cmd="sudo -S dnf autoremove -yq"
+  fi
+
+  if echo "$password" | eval "$cmd"; then
     ansi --green "Orphans removed."
   else
     ansi --red "Error occured"
@@ -202,7 +230,13 @@ fi
 if [[ $_arg_flatpak == 'on' ]]; then
   ansi --blue "Updating flatpak apps..."
 
-  if flatpak update -y; then
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="flatpak update -y"
+  else
+    cmd="flatpak update -y --noninteractive > /dev/null"
+  fi
+
+  if eval "$cmd"; then
     ansi --green "Flatpak apps updated."
   else
     ansi --red "Error occured."
@@ -225,57 +259,83 @@ fi
 if [[ $_arg_bin == 'on' ]]; then
   ansi --blue "Updating binaries in ~/bin..."
 
-  printf "\t"
+  printf "  "
   ansi --blue "Updating chezmoi..."
 
-  if chezmoi upgrade; then
-    printf "\t"
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="chezmoi upgrade"
+  else
+    cmd="chezmoi upgrade > /dev/null"
+  fi
+
+
+  if eval "$cmd"; then
+    printf "  "
     ansi --green "Chezmoi updated."
   else
-    printf "\t"
+    printf "  "
     ansi --red "Error occured."
   fi
 
   echo
-  printf "\t"
+  printf "  "
   ansi --blue "Updating addpath..."
 
-  if nim -d:release c ~/scripts/addpath.nim && mv ~/scripts/addpath ~/bin; then
-    printf "\t"
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="nim -d:release c ~/scripts/addpath.nim && mv ~/scripts/addpath ~/bin"
+  else
+    cmd="nim -d:release --hints:off c ~/scripts/addpath.nim && mv ~/scripts/addpath ~/bin"
+  fi
+
+  if eval "$cmd"; then
+    printf "  "
     ansi --green "Addpath updated."
   else
-    printf "\t"
+    printf "  "
     ansi --red "Error occured."
   fi
 
   echo
-  printf "\t"
+  printf "  "
   ansi --blue "Updating getpath..."
 
-  if nim -d:release c ~/scripts/getpath.nim && mv ~/scripts/getpath ~/bin; then
-    printf "\t"
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="nim -d:release c ~/scripts/getpath.nim && mv ~/scripts/getpath ~/bin"
+  else
+    cmd="nim -d:release --hints:off c ~/scripts/getpath.nim && mv ~/scripts/getpath ~/bin"
+  fi
+
+  if eval "$cmd"; then
+    printf "  "
     ansi --green "Getpath updated."
   else
-    printf "\t"
+    printf "  "
     ansi --red "Error occured."
   fi
 
   echo
-  printf "\t"
+  printf "  "
   ansi --blue "Updating xplr..."
 
-  if kernel_name=$(uname -s) && curl -LO "https://github.com/sayanarijit/xplr/releases/latest/download/xplr-${kernel_name,,}.tar.gz" && tar xzf "xplr-${kernel_name,,}.tar.gz" -C ~/bin && rm -rf "xplr-${kernel_name,,}.tar.gz"; then
-    printf "\t"
+  kernel_name=$(uname -s)
+  xplr_url="https://github.com/sayanarijit/xplr/releases/latest/download/xplr-${kernel_name,,}.tar.gz"
+
+  if [[ $_arg_verbose == "on" ]]; then
+    cmd="curl -LO $xplr_url"
+  else
+    cmd="curl -LOs $xplr_url"
+  fi
+
+  if eval "$cmd" && tar xzf "xplr-${kernel_name,,}.tar.gz" -C ~/bin && rm -rf "xplr-${kernel_name,,}.tar.gz"; then
+    printf "  "
     ansi --green "Xplr updated."
   else
-    printf "\t"
+    printf "  "
     ansi --red "Error occured."
   fi
 
 fi
+echo
 ansi --green "System updated."
-
-
-# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
 
 # ] <-- needed because of Argbash
