swap order of parameters

diff --git a/scripts/executable_upd b/scripts/executable_upd
--- a/scripts/executable_upd
+++ b/scripts/executable_upd
@@ -3,8 +3,8 @@
 # ARG_OPTIONAL_BOOLEAN([system],[s],[Update system packages])
 # ARG_OPTIONAL_BOOLEAN([autoremove],[r],[Remove orphans automatically])
 # ARG_OPTIONAL_BOOLEAN([flatpak],[f],[Update flatpak applications])
-# ARG_OPTIONAL_BOOLEAN([verbose],[v],[Enable verbose output])
 # ARG_OPTIONAL_BOOLEAN([neovim],[n],[Update neovim packages])
+# ARG_OPTIONAL_BOOLEAN([verbose],[v],[Enable verbose output])
 # ARG_HELP([Upd - little wrapper to update system])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -24,7 +24,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='srfvnh'
+	local first_option all_short_options='srfnvh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -33,19 +33,19 @@ begins_with_short_option()
 _arg_system="off"
 _arg_autoremove="off"
 _arg_flatpak="off"
-_arg_verbose="off"
 _arg_neovim="off"
+_arg_verbose="off"
 
 
 print_help()
 {
 	printf '%s\n' "Upd - little wrapper to update system"
-	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-v|--(no-)verbose] [-n|--(no-)neovim] [-h|--help]\n' "$0"
+	printf 'Usage: %s [-s|--(no-)system] [-r|--(no-)autoremove] [-f|--(no-)flatpak] [-n|--(no-)neovim] [-v|--(no-)verbose] [-h|--help]\n' "$0"
 	printf '\t%s\n' "-s, --system, --no-system: Update system packages (off by default)"
 	printf '\t%s\n' "-r, --autoremove, --no-autoremove: Remove orphans automatically (off by default)"
 	printf '\t%s\n' "-f, --flatpak, --no-flatpak: Update flatpak applications (off by default)"
-	printf '\t%s\n' "-v, --verbose, --no-verbose: Enable verbose output (off by default)"
 	printf '\t%s\n' "-n, --neovim, --no-neovim: Update neovim packages (off by default)"
+	printf '\t%s\n' "-v, --verbose, --no-verbose: Enable verbose output (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -92,18 +92,6 @@ parse_commandline()
 					{ begins_with_short_option "$_next" && shift && set -- "-f" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
-			-v|--no-verbose|--verbose)
-				_arg_verbose="on"
-				test "${1:0:5}" = "--no-" && _arg_verbose="off"
-				;;
-			-v*)
-				_arg_verbose="on"
-				_next="${_key##-v}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					{ begins_with_short_option "$_next" && shift && set -- "-v" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
 			-n|--no-neovim|--neovim)
 				_arg_neovim="on"
 				test "${1:0:5}" = "--no-" && _arg_neovim="off"
@@ -114,6 +102,18 @@ parse_commandline()
 				if test -n "$_next" -a "$_next" != "$_key"
 				then
 					{ begins_with_short_option "$_next" && shift && set -- "-n" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-v|--no-verbose|--verbose)
+				_arg_verbose="on"
+				test "${1:0:5}" = "--no-" && _arg_verbose="off"
+				;;
+			-v*)
+				_arg_verbose="on"
+				_next="${_key##-v}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-v" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
 			-h|--help)
